eks

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -43,9 +43,19 @@ jobs:
           name: tfplan
           path: ./tfplan
 
+      - name: Debug Terraform State
+        run: |
+          terraform state list
+        working-directory: ./
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ap-south-1
+
       - name: Terraform Apply
         if: github.event_name == 'push'
-        run: terraform apply -auto-approve ./tfplan
+        run: |
+          terraform apply -auto-approve ./tfplan || echo "Terraform apply failed; review state and plan."
         working-directory: ./
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -61,6 +71,7 @@ jobs:
       - name: Build Docker Image
         run: |
           docker build -t demo-worley-nc-ecr .
+
       - name: Tag Docker Image
         run: |
           docker tag demo-worley-nc-ecr:latest 484907523966.dkr.ecr.ap-south-1.amazonaws.com/demo-worley-nc-ecr:latest
