eks

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -45,7 +45,10 @@ jobs:
 
       - name: Debug Terraform State
         run: |
+          echo "Listing Terraform State:"
           terraform state list
+          echo "Outputs from Terraform:"
+          terraform output
         working-directory: ./
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -55,7 +58,7 @@ jobs:
       - name: Terraform Apply
         if: github.event_name == 'push'
         run: |
-          terraform apply -auto-approve ./tfplan || echo "Terraform apply failed; review state and plan."
+          terraform apply -auto-approve tfplan || echo "Terraform apply failed; review state and plan."
         working-directory: ./
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
